name: get_post
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  get_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get file list
        id: get_root_file_list
        run: |
          find . -type f -not -path './.git/*' -not -path './.github/*' > avge/root_list.txt

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./avge
          branch: master
          clean: true
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
