name: GetRepofiles
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  get_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get file list
        id: get_root_file_list
        run: |
          find . -type f -not -path './.git/*' -not -path './.github/*' > root_list.txt

      - name: Clean up worktree
        run: |
          git worktree prune
          git worktree remove --force github-pages-deploy-action-temp-deployment-folder || true
          git worktree list | awk '{print $1}' | xargs -I {} git worktree remove --force {} || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # folder: ./avge
          branch: gh-pages # The branch the action should deploy to.
          clean: false
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
